# Generated by Django 4.0.3 on 2023-01-12 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='شماره تماس')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=500, verbose_name='ادرس')),
                ('video', models.FileField(blank=True, null=True, upload_to='Trailer', verbose_name='تیزر')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='InfoUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('Confirmation', models.BooleanField(default=False, verbose_name='تایید')),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='شماره تماس')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=500, verbose_name='ادرس')),
                ('tags', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='Trailer', verbose_name='تیزر')),
                ('top', models.IntegerField(default=0, verbose_name='rank')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categorymodel', verbose_name='دسته بندی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.citymodel', verbose_name='شهر')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.regioncitymodel', verbose_name='منطقه')),
                ('subcategory', models.ManyToManyField(blank=True, null=True, to='categories.subcategorymodel', verbose_name='زیر مجموعه 1')),
                ('subtitle', models.ManyToManyField(blank=True, null=True, to='categories.subtitlemodel', verbose_name='زیر مجموعه 2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.villagemodel', verbose_name='روستا')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'اصناف',
            },
        ),
        migrations.CreateModel(
            name='ProductsAnotherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('preview', models.ImageField(upload_to='ProductsPreviewAnother')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.BigIntegerField(null=True, verbose_name='قیمت')),
                ('created', models.DateField(default=datetime.datetime(2023, 1, 12, 12, 1, 31, 41808, tzinfo=utc))),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('infouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infousers.infousermodel', verbose_name='صنف')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='VerifyCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('code', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('valid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(blank=True, null=True, upload_to='ShopImage', verbose_name='تصویر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تصویر صنف',
                'verbose_name_plural': 'تصاویر اصناف',
            },
        ),
        migrations.CreateModel(
            name='QuestionProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categorymodel', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سوالات صنف',
                'verbose_name_plural': 'سوالات اصناف',
            },
        ),
        migrations.CreateModel(
            name='ProductsImageAnotherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductsPreviewAnotherImage', verbose_name='تصویر')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infousers.productsanothermodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
        migrations.CreateModel(
            name='ManagerStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('category', models.ManyToManyField(to='categories.categorymodel', verbose_name='دسته بندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مدیریت صنف',
                'verbose_name_plural': 'مدیریت اصناف',
            },
        ),
        migrations.CreateModel(
            name='AnswerProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infousers.questionprofilemodel', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ سوال',
                'verbose_name_plural': 'پاسخ سوالات',
            },
        ),
    ]
