# Generated by Django 4.0.3 on 2023-01-12 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infousers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsanothermodel',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 12, 3, 27, 283920, tzinfo=utc)),
        ),
    ]
