# Generated by Django 4.0.3 on 2023-01-12 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infousers', '0002_alter_productsanothermodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousermodel',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='productsanothermodel',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 12, 30, 50, 293590, tzinfo=utc)),
        ),
    ]
