# Generated by Django 4.0.3 on 2023-01-12 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infousers', '0003_alter_infousermodel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='productsanothermodel',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 1, 12, 12, 32, 48, 433349, tzinfo=utc)),
        ),
    ]
