# Generated by Django 4.0.3 on 2023-01-12 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='خبر')),
            ],
            options={
                'verbose_name': 'دسته بندی خبر',
                'verbose_name_plural': 'دسته بندی اخبار',
            },
        ),
        migrations.CreateModel(
            name='TopNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='office.officemodel', verbose_name='اداره')),
            ],
            options={
                'verbose_name': 'اخبار برتر',
                'verbose_name_plural': 'اخبار برتر',
            },
        ),
        migrations.CreateModel(
            name='NewsPeopleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='نام')),
                ('titr', models.CharField(max_length=500, verbose_name='تیتر')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='NewsPeople', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='TrailerNewsPeople', verbose_name='ویدیو')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 12, 12, 1, 31, 46868))),
                ('submit', models.BooleanField(default=False, verbose_name='تایید')),
                ('top', models.IntegerField(default=0, verbose_name='اولویت')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.citymodel', verbose_name='شهر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اخبار مردم',
                'verbose_name_plural': 'اخبار مردم',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titr', models.CharField(max_length=500, verbose_name='تیتر')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='News', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='TrailerNewsOffice', verbose_name='تیزر')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 12, 12, 1, 31, 47111))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorynewsmodel', verbose_name='دسته بندی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.citymodel', verbose_name='شهر')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.officemodel', verbose_name='اداره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.userofficemodel', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
    ]
