# Generated by Django 4.0.3 on 2023-01-12 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsmodel_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 12, 12, 30, 50, 297625)),
        ),
        migrations.AlterField(
            model_name='newspeoplemodel',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 12, 12, 30, 50, 297397)),
        ),
    ]
