# Generated by Django 4.0.3 on 2023-01-12 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('infousers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEstateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeestate', models.CharField(choices=[('edareAndTejari', 'اداری و تجاری'), ('masconi', 'مسکونی')], max_length=100, verbose_name='نوع')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'نوع ملک',
                'verbose_name_plural': 'نوع ملک ها',
            },
        ),
        migrations.CreateModel(
            name='ProductsEstateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('price', models.BigIntegerField(null=True, verbose_name='قیمت')),
                ('rent', models.BigIntegerField(null=True, verbose_name='اجاره')),
                ('mortgage', models.BigIntegerField(null=True, verbose_name='رهن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('image', models.ImageField(upload_to='ImageEstatePreview', verbose_name='تصویر')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('year', models.IntegerField(verbose_name='سال ساخت')),
                ('BuildingArea', models.IntegerField(verbose_name='متراژ بنا')),
                ('LanArea', models.IntegerField(verbose_name='متراژ زمین')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('warehouse', models.BooleanField(default=False, verbose_name='انباری')),
                ('balcony', models.BooleanField(default=False, verbose_name='بالکن')),
                ('room', models.IntegerField(blank=True, null=True, verbose_name='اتاق')),
                ('created', models.DateField(default=datetime.datetime(2023, 1, 12, 12, 1, 31, 43588, tzinfo=utc))),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('TypeEstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.typeestatemodel', verbose_name='نوع ملک')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.citymodel', verbose_name='شهر')),
                ('infouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infousers.infousermodel', verbose_name='صنف')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.regioncitymodel')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.villagemodel', verbose_name='روستا')),
            ],
            options={
                'verbose_name': 'محصول املاک',
                'verbose_name_plural': 'محصولات املاک',
            },
        ),
        migrations.CreateModel(
            name='ImageEstateProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImageEstateProducts')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.productsestatemodel')),
            ],
            options={
                'verbose_name': 'تصاویر محصولات املاک',
                'verbose_name_plural': 'تصاویر محصولات املاک',
            },
        ),
    ]
