# Generated by Django 4.0.3 on 2023-01-13 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_alter_productsestatemodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsestatemodel',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 17, 50, 7, 730999, tzinfo=utc)),
        ),
    ]
