# Generated by Django 4.0.3 on 2023-01-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, verbose_name='نام')),
                ('icon', models.ImageField(upload_to='category')),
                ('top', models.IntegerField(default=0, verbose_name='rank')),
                ('isProducts', models.BooleanField(default=False)),
                ('isPrice', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categorymodel', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'زیر مجوعه 1',
                'verbose_name_plural': 'زیر مجموعه 1',
            },
        ),
        migrations.CreateModel(
            name='VillageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.citymodel', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'روستا',
                'verbose_name_plural': 'روستا ها',
            },
        ),
        migrations.CreateModel(
            name='SubtitleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategorymodel', verbose_name='زیرمجموعه 1')),
            ],
            options={
                'verbose_name': 'زیر مجوعه 2',
                'verbose_name_plural': 'زیر مجموعه 2',
            },
        ),
        migrations.CreateModel(
            name='RegionCityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.citymodel', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'منطقه شهر',
                'verbose_name_plural': 'منطقه شهر',
            },
        ),
    ]
