# Generated by Django 4.0.3 on 2023-01-12 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infousers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransportationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeTransportation', models.CharField(choices=[('bycecle', 'دوچرخه'), ('motorcycle', 'موتور'), ('car', 'ماشین')], max_length=100, verbose_name='زیر مجموعه')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'زیر مجموعه محصولات حمل و نقل1',
                'verbose_name_plural': 'زیر مجموعه محصولات حمل و نقل1',
            },
        ),
        migrations.CreateModel(
            name='SubTypeTransportationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('TypeTransportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.typetransportationmodel', verbose_name='زیر مجموعه')),
            ],
            options={
                'verbose_name': 'زیر مجموعه محصولات حمل و نقل2',
                'verbose_name_plural': 'زیر مجموعه محصولات حمل و نقل2',
            },
        ),
        migrations.CreateModel(
            name='ProductsTransportationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImageTransportationPreview', verbose_name='تصویر')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('used', models.BigIntegerField(null=True, verbose_name='کارکرده')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('description', models.TextField(null=True, verbose_name='توضیحات')),
                ('created', models.DateField(default=datetime.datetime(2023, 1, 12, 12, 1, 31, 44811, tzinfo=utc))),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('SubTypeTransportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.subtypetransportationmodel', verbose_name='زیرمجموعه2')),
                ('TypeTransportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.typetransportationmodel', verbose_name='زیرمجموعه1')),
                ('infouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infousers.infousermodel', verbose_name='صنف')),
            ],
            options={
                'verbose_name': 'محصولات حمل و نقل',
                'verbose_name_plural': 'محصولات حمل و نقل',
            },
        ),
        migrations.CreateModel(
            name='ImageTransportationroductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImageTransportatioProducts', verbose_name='تصویر')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.productstransportationmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصاویر محصولات حمل و نقل',
                'verbose_name_plural': 'تصاویر محصولات حمل و نقل',
            },
        ),
    ]
