# Generated by Django 4.0.3 on 2023-01-12 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('address', models.CharField(max_length=500, verbose_name='ادرس')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ImageField(upload_to='ProfileOffice', verbose_name='پروفایل')),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lng', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='TrailerOffice', verbose_name='تیزر')),
                ('number', models.BigIntegerField(blank=True, null=True, verbose_name='شماره تماس')),
                ('preview', models.ImageField(upload_to='PreviewOffice', verbose_name='عکس نمایه')),
                ('icon', models.ImageField(upload_to='IconOffice', verbose_name='ایکون')),
                ('top', models.IntegerField(default=0, verbose_name='اولویت')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.citymodel', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'اداره',
                'verbose_name_plural': 'ادارات',
            },
        ),
        migrations.CreateModel(
            name='UserOfficeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.officemodel', verbose_name='اداره ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'افراد ادره',
                'verbose_name_plural': 'افراد اداره',
            },
        ),
    ]
