# Generated by Django 4.0.3 on 2023-01-12 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('typeask', models.CharField(choices=[('complaint', 'شکایت'), ('criticism', 'شکایت و پیشنهاد')], max_length=100, verbose_name='نوع تیکت')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isfinish', models.BooleanField(default=False, verbose_name='تموم شده')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.officemodel', verbose_name='اداره')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.userofficemodel', verbose_name='کارکن اداره')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='MessageTicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ImageTicket', verbose_name='تصویر')),
                ('video', models.FileField(blank=True, null=True, upload_to='VideoTicket', verbose_name='ویدیو')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isread', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticketmodel', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
